name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Wait for MongoDB
        run: |
          while ! nc -z localhost 27017; do
            echo "Waiting for MongoDB to start...";
            sleep 1;
          done

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./... -v
