name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: make build

    - name: Wait for MongoDB
      run: |
        until docker exec $(docker ps -q -f ancestor=mongo:latest) mongo --eval 'db.runCommand({ ping: 1 })'; do
          echo "Waiting for MongoDB to be ready..."
          sleep 2
        done

    - name: Test
      run: make test
